[package]
name = "moon_os"
version = "0.1.0"
authors = ["Emoon <gustavo.chicato@usp.br>"]
edition = "2018"

# Abort on panic when running `cargo build`
[profile.dev]
panic = "abort"

# Ditto, for `cargo build --release`
[profile.release]
panic = "abort"
