[package]
name = "moon_os"
version = "0.1.0"
authors = ["Emoon <gustavo.chicato@usp.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Abort on panic when running `cargo build`
[profile.dev]
panic = "abort"

# Ditto, for `cargo build --release`
[profile.release]
panic = "abort"
