[package]
name = "moon_os"
version = "0.1.0"
authors = ["Emoon <gustavo.chicato@usp.br>"]
edition = "2018"

[dependencies]
bootloader = "0.9.8"  # assists creation of bootable image
volatile = "0.2.6"    # allow definition of volatible variables to avoid compiler optimizing away data
